### ISSUE TITLE
Fair scoring model for pull requests

### ISSUE THREAD

**Issue by botezatunear** [NEAR-DevHub/devbot#1]
Define the approach to score PRs that participate in Sloth. Things to consider:

- scoring should be friendly for newcomers and don't reward only full-time developers
- scoring should not affect the normal workflow (e.g., splitting one PR into multiple to get more rewards)
- scoring should not be easily abusable in a way it would lower the overall appreciation from maintainers

**Comment by ftdgoodluck** [comment]
May, 3rd call discussions:

- a combination of difficulty + how game-changing is the certain PR + time spent by maintainer
- a combination of abstract "value" for the project + time spent by the maintainer
- a combination of difficulty + impact

Additional notes:

- should be fairly easy for the maintainer to respond (fewer parameters are better)
- in any case, any time of abstract scoring might be biased

No final decision made

**Comment by botezatunear** [comment]
- Finally we were agreed that such parameters like Difficulty, Game Changer, Time consuming (for contributor) could be aggregated to "Value for the project".
- Besides that "Culture" of PR should be take into account as well, i.e. if Maintainer didn't spend extra time to accept this PR. Roughly I would estimate this parameter with 0.5 coefficient
- AI for Scoring looks like a promising have option, but more investigation requires - need to create a task for Launch milestone @ftdgoodluck 
- To incentivize newcomers we could implement "Boost" x2 for first 10 pull requests (or first 100 score points will be achieved)

**Comment by botezatunear** [comment]
We agreed to implement simple approach for MVP: 

- One score "Value" by Fibonacci sequence and include an option to make Score = 0
- No Boost for newcomers
- No additional Scores or parameters to measure PR
- Round to the nearest in case Score isn't a number of Fibonacci sequence (7=>8, 14=>13), round to lower in case of the middle (4=>3, 17=>13)
