### ISSUE TITLE
Research potential ways to implement the bot

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#2]
We need to understand potential options to implement interactions with Sloth inside 3rd party open-source repositories considering the following:

- we should not implement the necessity of breaking changes in PR review processes
- Sloth submission (ideally) could be implemented from the console git interface (?)
- Responses for PRs submitted for Sloth should be simple and take a max of an additional minute from the maintainer

**Comment by ftdgoodluck** [comment]
first research by @akorchyn https://hackmd.io/@yurtur/SJi1-ebfR

**Comment by akorchyn** [comment]
After the call, we have decided to go with the userbot implementation.
