### ISSUE TITLE
Eligibility criteria for participants

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#36]
Decide who is eligible to participate in the Sloth race

**Comment by ftdgoodluck** [comment]
May 3rd call outcome:

Contributors:
- Since we won't have monetary rewards, we should not have any strong restrictions during MVP phase. Once we come closer to monetary rewards, we may think about downranking opensource contributors who are full-time employees of certain projects or any other type of ethical participation codex
Maintainers:
- we consider anybody who has merged a pull request a maintainer (or a PR approver in case of auto-merge done by a bot)
- if there are several reviewers, we calculate arithmetic mean of all submitted scores. All reviewers have a 24-hour window to submit scores once the first score was submitted

**Comment by akorchyn** [comment]
To be honest it shouldnt be hard to do. But up to you guys

**Comment by botezatunear** [comment]
In case maintainer doesn't allow full-time developer (with salary) to participate in Sloth Race, this person has a motivation to create a new account for participation and we should avoid it, for instance, by date of registration or overall profile.

**Comment by akorchyn** [comment]
I don't really understand how that motivation would work. If he created a new account and start working with it - meantime hiding their identity - it won't get salary as no one see his results.

**Comment by ftdgoodluck** [comment]
Agreed that during MVP stage we don't limit anybody, may be reviewed based on statistics we'll collect during MVP
