### ISSUE TITLE
Contributor customer development

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#4]
Run a series of interviews with potential contributors that would join on the MVP stage

**Comment by ftdgoodluck** [comment]
we can test the approach inside DevHub only, then we will invite others from other organizations (near, aurora, etc.)

**Comment by frol** [comment]
@akorchyn We need to be able to whitelist individual repositories and whole orgs.

For MVP, let's whitelist:

* [ ] https://github.com/NEAR-DevHub org (we will test the bot implementation here)
* [ ] https://github.com/near org
* [ ] https://github.com/near-examples org
* [ ] https://github.com/calimero-network org
* [ ] https://github.com/aurora-is-near org
* [ ] https://github.com/NearSocial org
* [ ] https://github.com/fastnear org
* [ ] https://github.com/near-cli-rs org
* [ ] https://github.com/bos-cli-rs org

We can reach out to the first cohort of adopters via:

* https://t.me/NEAR_Tools_Community_Group
* https://near.zulipchat.com/#narrow/stream/295302-general

**Comment by frol** [comment]
@botezatunear @ftdgoodluck Is this enough for the current milestone? Should we create a new issue for the launch milestone or keep this one?

**Comment by botezatunear** [comment]
For MVP the list is enough, let's create a new issue for launch milestone @ftdgoodluck

**Comment by ftdgoodluck** [comment]
@frol @botezatunear created #42 for the Launch milestone, closing this as done - looks good for MVP
