### ISSUE TITLE
Allocate the team and budget for MVP

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#5]

**Comment by botezatunear** [comment]
Draft:

https://docs.google.com/spreadsheets/d/1bMe6lDTy3tewO7O0WyJxSqkOg8nFAP6enr2SWbDRH4c/edit#gid=0

**Comment by botezatunear** [comment]
https://docs.google.com/spreadsheets/d/1bMe6lDTy3tewO7O0WyJxSqkOg8nFAP6enr2SWbDRH4c/edit#gid=0
