### ISSUE TITLE
bot message - scoring

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#97]
-------correct non-zero-scoring-----------

### 🌟 Score recorded! 
@ftdgoodluck, thank you for scoring this pull request in the Race of Sloths!

---------correct-zero-scoring---------------

### 0⃣️ Score recorded! 

@ftdgoodluck Keep your spirits up! Every contribution is a learning opportunity, and your effort is genuinely appreciated. 

--------------corrected-non-zero-scoring--------

### 🏆 Score recorded! 
It looks like @ftdgoodluck provided a score of 9, but based on our Fibonacci scoring rules, we've adjusted it to 8.
> [!TIP]
We accept only the following Fibonacci numbers [0, 1, 2, 3, 5, 8, 13] for scoring

--------------corrected-exclude-message--------
### 🙁 Pull request excluded
Probably, it is not something that the project needs right now

**Comment by akorchyn** [comment]
![image](https://github.com/NEAR-DevHub/devbot/assets/42449190/49a75b34-24ad-44d4-8d48-a76209d38acf)
Looks broken on linux
