### ISSUE TITLE
bot message - error handling

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#99]
------------error_unknown_command_message------

### ❓Unknown command 
Please check the command and try again

---------error_rights_violation_message-----------
 
### 🚫 Access denied 
Only maintainers can use this command

---------error_late_include_message--------------

### ⏰️ PR is already merged
It's too late to include us now. Include us before the merge next time!

---------error_late_scoring_message------------

### ⏰️ Scoring closed
24 hours have already passed since the merge

----------pause_paused_message--------------

### ⏸️ This repository is already on pause

---------unpause_unpaused_message----------

### ▶️ The repo is already active

--------error_selfscore_message--------------

### ❌ Self-scoring is not permitted. 
Let's keep it fair! 👍

**Comment by akorchyn** [comment]
----------pause_paused_message--------------

Up to you, but currently, I ignore all commands except unpause for paused repo, so I think we can omit that.
